name: tests

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/action-setup@v6
            - name: Setup Node
              uses: actions/setup-node@v7
              with:
                  node-version-file: '.nvmrc'
                  cache: 'pnpm'
                  registry-url: 'https://npm.pkg.github.com'
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - run: pnpm test
